# Generated by Django 5.1.4 on 2025-02-04 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_address_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='features',
            name='product_id',
        ),
    ]
