# Generated by Django 5.1.4 on 2025-02-05 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_address_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='user_id',
        ),
    ]
